### ISSUE TITLE
Automatic analysis removal when deleting EEs

### ISSUE THREAD

**Issue by tesar-stepan** [ppavlidis/Gemma#15]
When deleting certain experiments, user can receive following error:
```
org.hibernate.util.JDBCExceptionReporter.logExceptions(233) | SQL Error: 1451, SQLState: 23000
org.hibernate.util.JDBCExceptionReporter.logExceptions(234) | Cannot delete or update a parent row: a foreign key constraint fails (`gemd`.`ANALYSIS`, CONSTRAINT `FKF19622DCED6A0A89` FOREIGN KEY (`EXPERIMENT_ANALYZED_FK`) REFERENCES `INVESTIGATION` (`ID`))
```
Paul via slack:
> I believe the reason that's happening is that we have coexpression analysis for it, and that needs to be deleted separately, and we don't have a specific CLI tool for that - it just doesn't come up often.
> My approach for a fix would be to add a delete option to the LinkAnalysisCli, to go directly to LinkAnalysisPersister.deleteAnalyses

**Comment by ppavlidis** [comment]
There was already a FIXME in the code about this in ExpressionExperimentService. I will add a reference to this issue there. 

@tesar-stepan this is what I referred to when we were discussing cleaning up some old tables and fields. That's the actual cause of the error in this case. But it's still true that when you delete experiments, coexpression is not removed so will fail if it exists for that experiment (again, this is  not a common occurrence because we don't delete experiments often; ones that are used for coexpression are even less likely to  come up for deletion; and we only run coexpression on a fraction of our studies).

For those reasons and deleting coexpression is likely to be very slow, it would be okay if this is a separate functionality as I've implemented it in the LinkAnalysisCLI.
