### ISSUE TITLE
Error on bulk-adding genes to a group

### ISSUE THREAD

**Issue by ppavlidis** [ppavlidis/Gemma#37]
http://www.chibi.ubc.ca/Gemma/geneGroupManager.html

In the gene pane, adding single genes via the search works; but adding in bulk by using the pop-up window fails with a javascript NPE ("cannot read property..."); console is not giving clues. 

Also GET http://www.chibi.ubc.ca/Gemma/images/logo/gemOnlyTiny.ico 404 (Not Found)

This page also yields server-side warnings - missing js bundle.

**Comment by tesar-stepan** [comment]
I added an extra null check, but it seems that this can only happen when trying to import a list of genes that all have a taxon different form the taxon of the group. Is it possible that that might have been the case with your data?

**Comment by ppavlidis** [comment]
They were gene symbols and as you know they are ambiguous about species, so I relied on the system to match them to the species chosen. Desired behaviour: If they don't match, they should just be left out. Ideally the user would be notified i.e. "99/100 genes were recognized".

Even if I had pasted in NCBI gene IDs, same thing should happen.

**Comment by tesar-stepan** [comment]
So the http://www.chibi.ubc.ca/Gemma/images/logo/gemOnlyTiny.ico 404 (Not Found) is fixed - I redirected it to the existing favicon file, but now for some reason the displayed favicon has a white background. 
The favicon was displayed properly before, and the line causing the 404 was meta.jsp:29
`<link rel="icon" href="<c:url value="/images/favicon.ico"/>"/>`
I'd suggest to remove this line alltogether, since modern browsers detect favicons automatically anyway.
